### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by robk9e** [epiclabs-io/hls-analyzer#7]
Hello
When I try to analyse the m2u8 the error below arise:

D:\kodi\hls-analyzer-master>python hls-analyzer.py -h http://hls.fearfulale.xyz/s/ch0003660/22a3687fa0f4048a2d8a671d5122b15c.m3u8
  File "hls-analyzer.py", line 119
    print "{0}".format(track.payloadReader.frames[j].type),
              ^
SyntaxError: invalid syntax

**Comment by robk9e** [comment]
The problem above was solved by installing the python 2.7.

But I'm receiving the error 403 Forbidden:

D:\kodi\hls-analyzer-master>c:\python27\python hls-analyzer.py http://hls.fearfulale.xyz/s/ch0003660/22a3687fa0f4048a2d8a671d5122b15c.m3u8
Traceback (most recent call last):
  File "hls-analyzer.py", line 197, in <module>
    m3u8_obj = m3u8.load(args.url)
  File "D:\kodi\hls-analyzer-master\m3u8\__init__.py", line 50, in load
    return _load_from_uri(uri)
  File "D:\kodi\hls-analyzer-master\m3u8\__init__.py", line 59, in _load_from_uri
    resource = urlopen(uri)
  File "c:\python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

In the vlc everything works well

**Comment by jeoliva** [comment]
Hi @robk9e, thanks for reporting the issue. The problem is related with the user-agent header. Hls-analyzer is not setting it and thats a requirement of your http server.

I will push a change to resolve this.

Thanks!

**Comment by jdinocco** [comment]
Hi, you have any progress on this? Thanks!

**Comment by inside83** [comment]
I'm getting the same
```
File "hls-analyzer.py", line 119`
    print "{0}".format(track.payloadReader.frames[j].type),
              ^
```
and installing python 2.7 didn't help 🤷‍♂️

**Comment by miadabdi** [comment]
Same here.
Three year old and still not solved?
